# Data Science for Calculus

## End of course assessment
### Instructions

1. You are to complete the whole workbook.
2. All algorithms have been provided.
3. Ask questions during Practical Applications session.


This is a Pass/Fail assessment. Show all your workings and comment on your choices and approaches through the assessment.

The neural net diagram (see below) will serve as a guide for naming comventions throughout this workbook. Refer to this diagram constantly.

![nn](neural_net.png)

### Imported Libraries

Place all libraries used for this workbook here:

In [2]:
import numpy as np
import pandas as pd
import math
from sklearn.preprocessing import add_dummy_feature

### Data

In [3]:
X_train = np.array([[4.7,1.4],[4.5,1.4],[4.9,1.5],[4.0,1.3],[4.1,1.0],[5.1,1.9],[6.1,2.5],[5.5,2.1],[6.0,1.8],[5.8,1.6]])
y_train = np.array([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

### Step 1 - Data Preparation

1. Review datset
2. Clean data set if needed
3. Comment on why you choose your particular cleaning strategy
4. Scale dataset if needed
5. Comment on why you choose you particular scaling strategy
6. Display data

In [4]:
X_train

array([[4.7, 1.4],
       [4.5, 1.4],
       [4.9, 1.5],
       [4. , 1.3],
       [4.1, 1. ],
       [5.1, 1.9],
       [6.1, 2.5],
       [5.5, 2.1],
       [6. , 1.8],
       [5.8, 1.6]])

Data does not need to be cleaned. All rows are filled.

In [5]:
# Will add a column of ones to represent intercept input
X_train = add_dummy_feature(X_train)
X_train

array([[1. , 4.7, 1.4],
       [1. , 4.5, 1.4],
       [1. , 4.9, 1.5],
       [1. , 4. , 1.3],
       [1. , 4.1, 1. ],
       [1. , 5.1, 1.9],
       [1. , 6.1, 2.5],
       [1. , 5.5, 2.1],
       [1. , 6. , 1.8],
       [1. , 5.8, 1.6]])

### Step 2 - Forward Propogation

Calculate the output for each hidden node and output node using the summation operator and activation function. Show the resulting matrix for each hidden node and output node.

1. Set the weights
2. Calulate the net input to nodes H1 and H2 with the summation operator
3. Apply the activation function to nodes H1 and H2
4. Calculate the net input for node O1 with the summation operator
5. Apply the activation function to node O1
6. Display the matrices for each step


#### Summation Operator

$\begin{align}\sum_{i=1}^{n} (a_i W_i) + bias \end{align}$

#### Activation Function

$\begin{align}F(x) = \frac{1}{(1+e^{-X})}\end{align}$

In [9]:
h1_weights = np.random.rand(3, 1)
h2_weights = np.random.rand(3, 1)
o1_weights = np.random.rand(3, 1)

h1_input = np.asscalar(X_train[0] @ h1_weights)
h2_input = np.asscalar(X_train[0] @ h2_weights)

In [10]:
h1_activated = 1/(1 + math.exp(-h1_input))
h2_activated = 1/(1 + math.exp(-h2_input))
o1_vals = pd.Series([1, h1_activated, h2_activated])
o1_vals

0    1.000000
1    0.997433
2    0.992120
dtype: float64

In [11]:
o1 = np.asscalar(o1_vals @ o1_weights)
o1 = 1/(1 + math.exp(-o1))
o1

0.7246217847641618

### Step 3 - Calculate the Total Error

#### Use SE as the cost function

$\begin{align} SE = \frac{1}{2} \sum_{i=1}^{n} (t_i - z_i)^2 \end{align}$

"t" is the target output and "z" is the actual output of the the output node.

Display total error

In [12]:
SE = ((o1 - y_train[0]) ** 2) / 2
SE

array([0.03791658])

### Step 4 - Calculate the Gradients

1. Calculate the gradients for output weights
2. Calculate the output layer bias weights
3. Calculate the gradients for hidden layer weights
4. Calculate the hidden layer bias weights
5. Display all gradients

In [16]:
# gradient = error * (x(1 - x)) * output of previous layer
w5_gradient = SE * (o1 * (1 - o1) * h1_activated)
w6_gradient = SE * (o1 * (1 - o1) * h2_activated)
we3_gradient = SE * (o1 * (1 - o1))
we1_gradient = (h1_activated * (1 - h1_activated)) * (we3_gradient * o1_weights[0])
we2_gradient = (h2_activated * (1 - h2_activated)) * (we3_gradient * o1_weights[0])
w1_gradient = (h1_activated * (1 - h1_activated)) * (we3_gradient * o1_weights[0]) * X_train[0][1]
w2_gradient = (h2_activated * (1 - h2_activated)) * (we3_gradient * o1_weights[0]) * X_train[0][1]
w3_gradient = (h1_activated * (1 - h1_activated)) * (we3_gradient * o1_weights[0]) * (X_train[0][2])
w4_gradient = (h2_activated * (1 - h2_activated)) * (we3_gradient * o1_weights[0]) * (X_train[0][2])

print("w1 gradient: ", w1_gradient)
print("w2 gradient: ", w2_gradient)
print("w3 gradient: ", w3_gradient)
print("w4 gradient: ", w4_gradient)
print("w5 gradient: ", w5_gradient)
print("w6 gradient: ", w6_gradient)
print("we1 gradient: ", we1_gradient)
print("we2 gradient: ", we2_gradient)
print("we3 gradient: ", we3_gradient)

w1 gradient:  [4.63728962e-05]
w2 gradient:  [0.00014161]
w3 gradient:  [1.38132031e-05]
w4 gradient:  [4.21811796e-05]
w5 gradient:  [0.00754665]
w6 gradient:  [0.00750645]
we1 gradient:  [9.86657366e-06]
we2 gradient:  [3.0129414e-05]
we3 gradient:  [0.00756607]


### Step 5 - Update the weights

1. Update the general weights
2. Update the bias weights
3. Display all weights


*Hint!*

$\begin{align} \begin{array}{rl} W_i \\ new \end{array} = W_i - \eta * \frac{\delta E}{\delta W_i} \end{align}$

In [19]:
h1_weights = h1_weights - 0.002 * np.array([we1_gradient, w1_gradient, w3_gradient])
h2_weights = h2_weights - 0.002 * np.array([we2_gradient, w2_gradient, w4_gradient])
o1_weights = o1_weights - 0.002 * np.array([we3_gradient, w5_gradient, w6_gradient])

print("h1 weights: ")
print(h1_weights)
print("h2 weights: ")
print(h2_weights)
print("o1 weights: ")
print(o1_weights)

h1 weights: 
[[0.05786953]
 [0.95916059]
 [0.99762454]]
h2 weights: 
[[0.07394736]
 [0.85528997]
 [0.52982454]]
o1 weights: 
[[0.50934735]
 [0.0232706 ]
 [0.43826423]]
