# Matrix Transformations and Decomposition

* __Author: Prof. Nagiza F. Samatova__
* __Email: samatova@csc.ncsu.edu__
* __Date: February 16, 2019__

In [1]:
import numpy as np
import matplotlib.pyplot as plt       
import sklearn.decomposition as decomposition
import sklearn.datasets as datasets

# Centering

In [2]:
x = np.array([2.1,2.5,4.0,3.6])
np.mean(x)

3.05

In [3]:
# Centered vector
xc = x - np.mean(x)
xc

array([-0.95, -0.55,  0.95,  0.55])

# Standardizing

In [4]:
x = np.array([2.1,2.5,4.0,3.6])
np.var(x,ddof=1) # compute the variance

0.8033333333333333

In [5]:
np.std(x,ddof=1) # compute standard deviation

0.8962886439832501

In [6]:
np.std(x,ddof=1)**2 # standard deviation squared

0.8033333333333333

In [8]:
xc * xc # centered vector squared

array([0.9025, 0.3025, 0.9025, 0.3025])

In [9]:
np.sum(xc * xc) # sum of squared centered vectors

2.41

In [10]:
np.sum(xc * xc)/(len(x)-1) # calculate the variance

0.8033333333333333

In [11]:
x/np.std(x,ddof=1) # standardizing using standard deviation

array([2.34299521, 2.78928001, 4.46284802, 4.01656322])

In [12]:
xc/np.std(x,ddof=1) # z-score: standardizing using mean and standard deviation

array([-1.0599264, -0.6136416,  1.0599264,  0.6136416])

In [13]:
# Standardizing: all steps in one

x = np.array([2.1,2.5,4.0,3.6])
var_x = np.var(x,ddof=1)
sd = np.std(x,ddof=1)
sd_squared = sd**2
xc_squared = xc**2
sum_xc_squared = np.sum(xc_squared)
var = sum_xc_squared/(len(x)-1)
xs = x/sd
z_score = xc/sd

print(round(var_x, 5))
print(round(sd, 5))
print(round(sd_squared, 5))
print(xc_squared)
print(round(sum_xc_squared, 2))
print(round(var, 5))
print(xs)
print(z_score)

0.80333
0.89629
0.80333
[0.9025 0.3025 0.9025 0.3025]
2.41
0.80333
[2.34299521 2.78928001 4.46284802 4.01656322]
[-1.0599264 -0.6136416  1.0599264  0.6136416]


# Covariance

In [14]:
x = np.array([2.1,2.5,4.0,3.6])
xc = x - np.mean(x) # centering
y = np.array([8,12,14,10])
yc = y - np.mean(y) # centering
norm_cross_prod = np.sum(np.matmul(xc.T,yc))/(len(y)-1) # normalized cross-product
print(norm_cross_prod)
np.cov(x,y)[1,0] # covariance

1.5333333333333332


1.5333333333333332