# Introduction to Matrix Algebra

* __Author: Prof. Nagiza F. Samatova__
* __Email: samatova@csc.ncsu.edu__
* __Date: February 15, 2019__

# Importing relevant packages 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial.distance as distance

# Vector Operators in Python

In [2]:
# Create an array from 0~11
x = range(12) 

# Create a 3x4 matrix from 0~11
A = np.reshape(range(12),(3,4))

In [3]:
x

range(0, 12)

In [4]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# Extract the diagonal cells of the matrix A
np.diag(A)

array([ 0,  5, 10])

In [6]:
# get the length of array x
len(x)

12

In [7]:
# Get the fourth element of array x
x[3]

3

# Matrix Operators

In [8]:
# Create a 3x4 matrix from 0~11
m = np.reshape(range(12),(3,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# Create a diagonal matrix from the diagonals of m
np.diag(np.diag(m))

array([[ 0,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 10]])

In [10]:
# Extract the diagonal cells of the matrix A, 
# starting from the second row/column (above the main diagonal)
np.diag(m, 1)

array([ 1,  6, 11])

In [12]:
# Extract the diagonal below the main diagonal
np.diag(m, -1)

array([4, 9])

In [13]:
# Create diagonal matrix 
# with values in diagonal declared in range
v = range(4)
np.diag(v, k=0)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [ ]:
np.matrix?

In [14]:
# Create matrix with np.matrix() - not recommended
np.matrix([[5, 6, 7], [2, 3, 4]])

matrix([[5, 6, 7],
        [2, 3, 4]])

In [15]:
# Create matrix with numpy array and np.asmatrix()
b = np.array([[1, 2], [3, 4]])
np.asmatrix(b)

matrix([[1, 2],
        [3, 4]])

In [16]:
# Find the shape of matrix
m.shape

(3, 4)

In [17]:
# Find the number of rows of matrix
m.shape[0]

3

In [18]:
# Find the number of columns of matrix
m.shape[1]

4

## Access rows/columns, subset of rows/columns in matrix

In [19]:
# Access the (i,j) element in matrix
m[1, 2]

6

In [20]:
# Access second row in matrix m

# m[1,:]
# m[1,]
m[1]

array([4, 5, 6, 7])

In [21]:
# Access second column in matrix m

m[:, 1]

array([1, 5, 9])

In [22]:
# To access a subset of rows in matrix m

# m[1:3, :]
m[1:3] 

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# To access a subset of columns in matrix m

m[:, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [24]:
#To access a sub-matrix

m [1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

# Matrix Operators

In [25]:
A = np.random.randint(1, 10, (2, 3))
B = np.random.randint(1, 10, (2, 3))
print(A)
print(B)

[[2 8 3]
 [5 6 5]]
[[7 1 7]
 [4 5 8]]


In [26]:
# Addition
A + B

array([[ 9,  9, 10],
       [ 9, 11, 13]])

In [27]:
# Subtraction
A - B

array([[-5,  7, -4],
       [ 1,  1, -3]])

In [28]:
# Hadamard (element-by-element) multiplication
A * B

array([[14,  8, 21],
       [20, 30, 40]])

In [29]:
# Matrix Transpose
A.T

array([[2, 5],
       [8, 6],
       [3, 5]])

In [30]:
C = np.random.randint(1, 10, (3, 3))
C

array([[4, 3, 7],
       [5, 7, 3],
       [5, 8, 6]])

In [31]:
# Inversion of A^(-1)
np.linalg.inv(C)

array([[ 0.29032258,  0.61290323, -0.64516129],
       [-0.24193548, -0.17741935,  0.37096774],
       [ 0.08064516, -0.27419355,  0.20967742]])

In [32]:
# Calculate Determinant of matrix
np.linalg.det(C) 

62.00000000000001

In [33]:
# Eigen-analysis of matrix
np.linalg.eig(C)

(array([15.99179473+0.j       ,  0.50410264+1.9033835j,
         0.50410264-1.9033835j]),
 array([[ 0.52427373+0.j        , -0.77356123+0.j        ,
         -0.77356123-0.j        ],
        [ 0.51722551+0.j        ,  0.41965768+0.27442243j,
          0.41965768-0.27442243j],
        [ 0.67647234+0.j        ,  0.20647395-0.32795014j,
          0.20647395+0.32795014j]]))

In [34]:
# Calculate Trace of matrix
np.sum(np.diag(C))

17

In [35]:
# Join two vectors into A as columns
np.concatenate((A,B),axis=1)

array([[2, 8, 3, 7, 1, 7],
       [5, 6, 5, 4, 5, 8]])

In [36]:
# Join two vectors into A as rows
np.concatenate((A,B),axis=0)

array([[2, 8, 3],
       [5, 6, 5],
       [7, 1, 7],
       [4, 5, 8]])

In [37]:
# Horizontal stack (join by col)
np.hstack((A,B))

array([[2, 8, 3, 7, 1, 7],
       [5, 6, 5, 4, 5, 8]])

In [38]:
# Vertical stack (join by row)
np.vstack((A,B))

array([[2, 8, 3],
       [5, 6, 5],
       [7, 1, 7],
       [4, 5, 8]])

# Matrix and Its Components

In [39]:
A = np.reshape([1,0,2,-6,3,0], (2,3))
A

array([[ 1,  0,  2],
       [-6,  3,  0]])

## Matrix Transpose, A'

In [40]:
A = np.reshape([1,0,2,-6,3,0], (2,3))
A

array([[ 1,  0,  2],
       [-6,  3,  0]])

In [41]:
B = A.T
B

array([[ 1, -6],
       [ 0,  3],
       [ 2,  0]])

In [42]:
B.T

array([[ 1,  0,  2],
       [-6,  3,  0]])

## Diagonal Matrix

In [43]:
A = np.reshape(np.array([1,0,0,2]),(2,2))
A

array([[1, 0],
       [0, 2]])

In [44]:
B = np.diag(np.array([1,0,0,2]))
B

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 2]])

In [45]:
np.fill_diagonal(A,5)
A

array([[5, 0],
       [0, 5]])

In [46]:
C = np.reshape(np.array([1,3,4,2]),(2,2))
C

array([[1, 3],
       [4, 2]])

In [47]:
np.diag(np.diag(C))

array([[1, 0],
       [0, 2]])

In [48]:
# Diagonal Matrix: all steps in one
A = np.reshape(np.array([1,0,0,2]),(2,2))
print(A)
B = np.diag(np.array([1,0,0,2]))
print(B)
np.fill_diagonal(A,5)
print(A)
C = np.reshape(np.array([1,3,4,2]),(2,2))
print(C)
np.diag(np.diag(C))

[[1 0]
 [0 2]]
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]]
[[5 0]
 [0 5]]
[[1 3]
 [4 2]]


array([[1, 0],
       [0, 2]])

## Identity Matrix

In [49]:
I = np.diag(np.array([1,1,1]))
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Trace of Square Matrix

In [50]:
C = np.reshape(np.array([1,3,4,2]),(2,2))
C

array([[1, 3],
       [4, 2]])

In [51]:
trace = np.sum(np.diag(C))
trace

3

## Matrix Operations: Element-by-Element

In [52]:
A = np.reshape([54,49,49,41,26,43,49,50,58,71],(5,2))
B = np.reshape(range(1,11),(5,2))
print(A)
print(B)

[[54 49]
 [49 41]
 [26 43]
 [49 50]
 [58 71]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [53]:
2*A+3

array([[111, 101],
       [101,  85],
       [ 55,  89],
       [101, 103],
       [119, 145]])

In [54]:
A+B

array([[55, 51],
       [52, 45],
       [31, 49],
       [56, 58],
       [67, 81]])

In [55]:
A-B

array([[53, 47],
       [46, 37],
       [21, 37],
       [42, 42],
       [49, 61]])

In [56]:
A/B

array([[54.        , 24.5       ],
       [16.33333333, 10.25      ],
       [ 5.2       ,  7.16666667],
       [ 7.        ,  6.25      ],
       [ 6.44444444,  7.1       ]])

## Inverses

In [58]:
A = np.reshape(np.array([2,3,3,4]),(2,2))

# Pay Attention: Declare type as float explicitly:
A = np.array(A, dtype=np.float)
A

array([[2., 3.],
       [3., 4.]])

In [59]:
# Check determinant of the matrix
np.linalg.det(A)

-1.0000000000000004

In [60]:
IA = np.linalg.inv(A)
IA

array([[-4.,  3.],
       [ 3., -2.]])

In [61]:
# Pay Attention: Declare type as float explicitly:
mul_1 = np.array(np.matmul(A,IA), dtype=np.float)
mul_1

array([[1., 0.],
       [0., 1.]])

In [62]:
# Pay Attention: Declare type as float explicitly:
mul_2 = np.array(np.matmul(IA,A), dtype=np.float)
mul_2

array([[1., 0.],
       [0., 1.]])

### If type was declared as int you are likely to get another result:

In [63]:
A = np.reshape(np.array([2,3,3,4]),(2,2))
A

array([[2, 3],
       [3, 4]])

In [64]:
# Check determinant of the matrix
np.linalg.det(A)

-1.0000000000000004

In [65]:
IA = np.linalg.inv(A)
IA

array([[-4.,  3.],
       [ 3., -2.]])

In [66]:
mul_1 = np.array(np.matmul(A,IA), dtype=np.int)
mul_1

array([[0, 0],
       [0, 1]])

In [67]:
mul_2 = np.array(np.matmul(IA,A), dtype=np.int)
mul_2

array([[0, 0],
       [0, 1]])

### Inverse of Inverse

In [68]:
A = np.reshape(np.array([2,3,3,4]),(2,2))
print(A)
IA = np.linalg.inv(A)
print(IA)

[[2 3]
 [3 4]]
[[-4.  3.]
 [ 3. -2.]]


### Inverse of Matrix Product

**(A x B)^(-1) = B^(-1) x A^(-1)**

In [69]:
A = np.reshape([2,3,3,4],(2,2),order='F')
A

array([[2, 3],
       [3, 4]])

In [70]:
B = np.reshape([3,4,2,3],(2,2),order='F')
B

array([[3, 2],
       [4, 3]])

In [71]:
C = np.matmul(A,B)
C

array([[18, 13],
       [25, 18]])

In [72]:
IC = np.linalg.inv(C)
IC

array([[-18.,  13.],
       [ 25., -18.]])

In [73]:
np.matmul(np.linalg.inv(B),np.linalg.inv(A))

array([[-18.,  13.],
       [ 25., -18.]])

In [74]:
# Inverse of Matrix product: all steps in one
A = np.reshape([2,3,3,4],(2,2),order='F')
print(A)
B = np.reshape([3,4,2,3],(2,2),order='F')
print(B)
C = np.matmul(A,B)
print(C)
IC = np.linalg.inv(C)
print(IC)
np.matmul(np.linalg.inv(B),np.linalg.inv(A))

[[2 3]
 [3 4]]
[[3 2]
 [4 3]]
[[18 13]
 [25 18]]
[[-18.  13.]
 [ 25. -18.]]


array([[-18.,  13.],
       [ 25., -18.]])

### Inverse of Transpose

**(A')^(-1) = (A^(-1))'**

In [76]:
A = np.reshape(np.array([2,3,3,4]),(2,2),order='F')
A

array([[2, 3],
       [3, 4]])

In [77]:
T = A.T
T

array([[2, 3],
       [3, 4]])

In [78]:
IT = np.linalg.inv(T)
IT

array([[-4.,  3.],
       [ 3., -2.]])

In [79]:
IA = np.linalg.inv(A)
IA

array([[-4.,  3.],
       [ 3., -2.]])

In [80]:
IA.T

array([[-4.,  3.],
       [ 3., -2.]])

In [81]:
# Inverse of Transpose Matrix: all steps in one
A = np.reshape(np.array([2,3,3,4]),(2,2),order='F')
T = A.T
print(A)
print(T)
IT = np.linalg.inv(T)
print(IT)
IA = np.linalg.inv(A)
print(IA.T)

[[2 3]
 [3 4]]
[[2 3]
 [3 4]]
[[-4.  3.]
 [ 3. -2.]]
[[-4.  3.]
 [ 3. -2.]]


### Existence of the Inverse Matrix, det(A)≠0

In [82]:
A = np.random.rand(4,4)
print(A)
np.linalg.det(A)

[[0.4775304  0.40616068 0.0373936  0.71191688]
 [0.54496922 0.66119175 0.9909438  0.38180032]
 [0.55479448 0.79926143 0.10601393 0.80504168]
 [0.54532223 0.20508427 0.13692587 0.76370174]]


0.00012285328635225535

### Transpose of the Matrix Product

**(A x B)' = B' x A'**

In [83]:
A = np.reshape(np.array([1,2,3,4,5,6]),(2,3))
A

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
B = np.reshape(np.array([1,2,3,4,5,6]),(3,2))
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
U = np.matmul(A,B)
U

array([[22, 28],
       [49, 64]])

In [86]:
U.T

array([[22, 49],
       [28, 64]])

In [87]:
V = np.matmul(B.T, A.T)
V

array([[22, 49],
       [28, 64]])

In [88]:
W = np.matmul(A.T, B.T)
W

array([[ 9, 19, 29],
       [12, 26, 40],
       [15, 33, 51]])

In [89]:
# Transpose of the Matrix product: all steps in one
A = np.reshape(np.array([1,2,3,4,5,6]),(2,3))
B = np.reshape(np.array([1,2,3,4,5,6]),(3,2))
U = np.matmul(A,B)
print(U.T)
V = np.matmul(B.T, A.T)
print(V)
W = np.matmul(A.T, B.T)
print(W)

[[22 49]
 [28 64]]
[[22 49]
 [28 64]]
[[ 9 19 29]
 [12 26 40]
 [15 33 51]]
